language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

script:
  - pytest
  - python -m pytest -v --cov tests --cov-report term-missing
  - pytest -v --cov tests --cov-report term-missing
  - nosetests -v --with-coverage --tests
after_success:
  - coveralls
deploy:
  provider: heroku
  api_key:
