language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest
  - nosetests -v --with-coverage --api
 
after_success:

  - coveralls
  - codeclimate-test-reporter
