language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

script:
  - pytest -v --cov api/app --cov-report term-missing
  - nosetests -v --with-coverage --api/app
 
after_success:

  - coveralls
